//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyCouriers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryInfo
    {
        public int DeliveryID { get; set; }
        public string PayStatus { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<int> DeltranID { get; set; }
    
        public virtual TransactionInfo TransactionInfo { get; set; }
    }
}
