//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyCouriers.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DeliveryMan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryMan()
        {
            this.TransactionInfoes = new HashSet<TransactionInfo>();
        }

        public int delmanID { get; set; }
        public string delmanName { get; set; }

        [DisplayName("User Email")]
        [Required(ErrorMessage = "This field is required.")]
        [DataType(DataType.EmailAddress)]
        public string delmanEmail { get; set; }

        [DisplayName("User Password")]
        [Required(ErrorMessage = "This field is required.")]
        [DataType(DataType.Password)]
        [MinLength(3, ErrorMessage = "Password Should be in 3 characters ")]
        public string delmanPass { get; set; }

        [Required(ErrorMessage = "Phone Number cannot be empty")]
        [DisplayName("User Phone")]
        [MaxLength(11, ErrorMessage = "Phone nummbers should be 11 digit.")]
        public string delmanPhone { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string delmanAddress { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string delmanStatus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionInfo> TransactionInfoes { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
