//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyCouriers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderInfo()
        {
            this.TransactionInfoes = new HashSet<TransactionInfo>();
        }
    
        public int orderID { get; set; }
        public Nullable<int> Order_userID { get; set; }
        public Nullable<int> Order_receiverID { get; set; }
        public Nullable<int> totalCost { get; set; }
        public string orderStatus { get; set; }
    
        public virtual userInformation userInformation { get; set; }
        public virtual receiverInfo receiverInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionInfo> TransactionInfoes { get; set; }
    }
}
