//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyCouriers.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class receiverInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receiverInfo()
        {
            this.OrderInfoes = new HashSet<OrderInfo>();
        }

        public int receiverID { get; set; }

        [Required(ErrorMessage = "Name cannot be empty")]
        [DisplayName("User Name")]
        public string receiverName { get; set; }

        [Required(ErrorMessage = "Address cannot be empty")]
        [DisplayName("User Adress")]
        public string receiverAddress { get; set; }


        public Nullable<System.DateTime> receiveDate { get; set; }

        [Required(ErrorMessage = "Product Type cannot be empty")]
        [DisplayName("User Product")]
        public string productType { get; set; }

        [Required(ErrorMessage = "Price cannot be empty")]
        [DisplayName("User Price")]
        public Nullable<int> productPrice { get; set; }

        [Required(ErrorMessage = "Phone Number cannot be empty")]
        [DisplayName("User Phone")]
        [MaxLength(11, ErrorMessage = "Phone nummbers should be 11 digit.")]
        [DataType(DataType.PhoneNumber)]
        public string phoneNumber { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
    }
}