//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyCouriers.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class userInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userInformation()
        {
            this.OrderInfoes = new HashSet<OrderInfo>();
        }

        public int userID { get; set; }

        public string Name { get; set; }

        [DisplayName("User Password")]
        [Required(ErrorMessage = "This field is required.")]
        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "Password Should be in 4 characters ")]
        public string Userpassword { get; set; }

        [DisplayName("User Email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "This field is required.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This field is required!")]
        public string UserRole { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
